### ISSUE TITLE
Unknown / Unhandled data types(s): u

### ISSUE THREAD

**Issue by r3wt** [naholyr/js-php-unserialize#10]
using `unserialize()`:
```
SyntaxError: Unknown / Unhandled data type(s): u
    at error (/usr/share/nginx5/realtime/node_modules/php-unserialize/php-unserialize.js:54:13)
    at _unserialize (/usr/share/nginx5/realtime/node_modules/php-unserialize/php-unserialize.js:166:11)
    at Object.unserialize (/usr/share/nginx5/realtime/node_modules/php-unserialize/php-unserialize.js:173:10)
```
using `unserializeSession`:
```
/usr/share/nginx5/realtime/node_modules/php-unserialize/php-unserialize.js:201
        throw new Error('Parse error on part "' + part + '"');
        ^

Error: Parse error on part "O:21:"App\Model\User"
```

whats the fucking point if it can't even unserialize an object?

**Comment by azeemigi** [comment]
SyntaxError: Unknown / Unhandled data type(s): o
    at error (/hidden/node_modules/php-unserialize/php-unserialize.js:54:13)

Can't this tool unserializeSession data when it contains objects (i.e. stdClass)?

**Comment by naholyr** [comment]
Duplicates #11
